import get from 'lodash/get';
import axios from 'axios';
import config from '@config';
import Image from 'next/image';
import { Product as ProductModel } from 'models/product';
import Head from 'next/head';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { useRouter } from 'next/router';
import { faCircleArrowLeft } from '@fortawesome/free-solid-svg-icons';
interface ProductProps {
  data: ProductModel;
}
const Product = (props: ProductProps) => {
  const {
    data: { title, category, price, image },
  } = props;
  const router = useRouter();
  return (
    <>
      <Head>
        <title>
          {config.PROJECT} - {title}
        </title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <button
          onClick={() => {
            router.back();
          }}
        >
          <FontAwesomeIcon
            icon={faCircleArrowLeft}
            height={50}
            color='darkBlue'
          />
        </button>
        <Image src={image} width={200} height={200} alt={title} />
        <h1>{title}</h1>
        <p>{category}</p>
        <p>{price}</p>
      </div>
    </>
  );
};

export default Product;

export const getServerSideProps = async (context: any) => {
  const productId = get(context, 'query.id', '');
  const response = await axios.get(`${config.BASE_URL}/products/${productId}`);
  return {
    props: {
      data: response?.data || {},
    },
  };
};
