import Head from 'next/head';
import config from 'config';
import ProductList from 'elements/ProductList';
import axios from 'axios';
import get from 'lodash/get';
const ProductCategory = (props: any) => {
  return (
    <div>
      <Head>
        <title>{config.PROJECT}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <ProductList data={props.data} />
    </div>
  );
};

export default ProductCategory;

export const getServerSideProps = async (context: any) => {
  const categoryName = get(context, 'query.id', '');
  const getCategories = await axios.get(
    `${config.BASE_URL}/products/categories/`
  );
  const getProducts = await axios.get(
    `${config.BASE_URL}/products/category/${categoryName}`
  );
  return {
    props: {
      data: {
        categories: getCategories.data,
        products: getProducts.data,
      },
    },
  };
};
