import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import config from 'config'
import ProductList from 'elements/ProductList'
import axios from 'axios'
const Home: NextPage = (props:any) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>{config.PROJECT}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
          <ProductList data={props.data}/>
      </div>
  )
}

export default Home


export const getServerSideProps = async () => {

  const getCategories = await axios.get(`${config.BASE_URL}/products/categories/`);
  const getProducts = await axios.get(`${config.BASE_URL}/products`);  
  return {
    props:{
      data:{
        categories : getCategories.data,
        products: getProducts.data
      }
    }
  }
}